### ISSUE TITLE
Remove pv.yaml from longhorn installation instructions

### ISSUE THREAD

**Issue by malikons** [civo/kubernetes-marketplace#115]
While trying to use longhorn for persistent storage in my civo k8s cluster, I encountered an issue where the pod was failing to mount the volume:

`3m43s       Warning   FailedAttachVolume   pod/plaindb-86dcdfb76-ppcl9   AttachVolume.Attach failed for volume "plaindb-volume" : attachdetachment timeout for volume plaindb-volume`
`2m8s        Warning   FailedMount          pod/plaindb-86dcdfb76-ppcl9   Unable to attach or mount volumes: unmounted volumes=[plaindb-volume], unattached volumes=[default-token-vwkvg plaindb-volume]: timed out waiting for the condition`

After a lot of troubleshooting it turned out that PV creation was causing the issue. So, when using longhorn with civo, we just need to create a claim and use that claim in the pod / deployment or whatever manifest you want to use. Creating PV beforehand causes some issues with the volume creation in the backend.

Can you please remove pv.yaml example from longhorn/post_install.md file, or at least put a note that PV creation is not needed and might cause issues.

**Comment by DoNnMyTh** [comment]
@malikons, can you ckeck if your issue is resolved :)

**Comment by saiyam1814** [comment]
Closing the issue, feel free to open if the issue still persists.
