### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by gdeepak884** [civo/kubernetes-marketplace#120]
This issue is a: Bug Report

Due to security reasons of your company, i am adding a link that will ask for request access to view this report.

[Bug Report](https://docs.google.com/document/d/1OE2emcGQsUFOq7EiDP1e9zALqRF116P58eLoiJ2XWZI/edit?usp=sharing)

**Comment by andyjeffries** [comment]
Thanks for this. I'm looking at it. Please do not accept any further requests for access (as this is a public repo others may find it and fake being from Civo)

**Comment by gdeepak884** [comment]
Can you please change the label, if you find this issue a valid kne

**Comment by andyjeffries** [comment]
We've fixed this issue, thank you for reporting it. Feel free to re-test, but we can no longer reproduce this.

**Comment by gdeepak884** [comment]
Yes, it's fixed
