### ISSUE TITLE
Add LitmusChaos: A cloud-native chaos engineering tool

### ISSUE THREAD

**Issue by ksatchit** [civo/kubernetes-marketplace#121]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[*] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
If you are requesting an enhancement to a feature already present, or a new feature, please outline below the feature you would like to see, and how it would benefit you and the wider Civo Kubernetes userbase:

## Bug Reports
If the issue is a Bug Report, please detail the following:

- Expected behaviour
- Encountered behaviour
- The steps to recreate the behaviour that you are reporting

If you have logs or screenshots, please include them below.

**Comment by saiyam1814** [comment]
We will get this added soon

**Comment by ksatchit** [comment]
The installation manifest is [here](https://litmuschaos.github.io/litmus/litmus-operator-v1.9.1.yaml). 

A recent article by @saiyam1814 around running litmus chaos experiments on civo cloud: https://www.civo.com/learn/chaos-engineering-kubernetes-litmus

**Comment by saiyam1814** [comment]
Closing as we have it in the marketplace now!! 
https://github.com/civo/kubernetes-marketplace/tree/master/litmuschaos
