### ISSUE TITLE
Add Hashicorp Vault

### ISSUE THREAD

**Issue by ayr-ton** [civo/kubernetes-marketplace#126]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[*] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
If you are requesting an enhancement to a feature already present, or a new feature, please outline below the feature you would like to see, and how it would benefit you and the wider Civo Kubernetes userbase:

This helm chart:
https://github.com/hashicorp/vault-helm
https://github.com/hashicorp/vault-helm/blob/master/values.yaml

Example of other apps using this chart:
https://docs.gitlab.com/ee/user/clusters/applications.html#install-vault-using-gitlab-cicd

**Comment by DoNnMyTh** [comment]
Hello @ayr-ton , Thank you for Request. Our marketplace is open to community to make contributions, and as we have updated our market place to support HELM3 and Install.sh files ( example -> https://github.com/civo/kubernetes-marketplace/blob/master/kubevious/install.sh) It is extremely easy. You are most welcome to make a Pull Request.

**Comment by dirsigler** [comment]
I really love this request, as I think a Civo Cluster is an awesome opportunity to have a running Vault Instance, which you can even configure to follow production grade best practices.

We should make sure that there are enough warnings, that a Vault installation without touching the [default values.yml](https://github.com/hashicorp/vault-helm/blob/master/values.yaml) results in a single-deployment installation of Vault without any HA features or auto-unseal.

**Comment by dirsigler** [comment]
I'll prepare something, but I don't know who to add as an maintainer. 
Maybe someone else knows who to add ?
