### ISSUE TITLE
'name' on delete action is not dynamically updating in almost whole website 

### ISSUE THREAD

**Issue by gdeepak884** [civo/kubernetes-marketplace#127]
This issue is a: functionallity issue

check the attacked video to reproduce.

[functionallity_issue.zip](https://github.com/civo/kubernetes-marketplace/files/5565602/functionallity_issue.zip)

**Comment by andyjeffries** [comment]
Thanks, but this doesn't relate to the Kubernetes Marketplace. https://github.com/civo/kube100 is the right repository. Other than that, this is a valid bug though so thanks.
