### ISSUE TITLE
Add Kafka

### ISSUE THREAD

**Issue by lspgn** [civo/kubernetes-marketplace#136]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[*] Feature request

## Enhancement suggestions / feature requests
If you are requesting an enhancement to a feature already present, or a new feature, please outline below the feature you would like to see, and how it would benefit you and the wider Civo Kubernetes userbase:

Example chart
https://bitnami.com/stack/kafka/helm

**Comment by DoNnMyTh** [comment]
Sure, We will give it a look to add.

**Comment by DoNnMyTh** [comment]
@saiyam1814 Kafka added with #178  issue can be closed
