### ISSUE TITLE
I would like to include Dapr.io

### ISSUE THREAD

**Issue by rajeshradhakrishnanmvk** [civo/kubernetes-marketplace#138]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[X ] Feature request

## Enhancement suggestions / feature requests
If you are requesting an enhancement to a feature already present, or a new feature, please outline below the feature you would like to see, and how it would benefit you and the wider Civo Kubernetes userbase:

I would like to add the app https://docs.dapr.io/ to Civo marketplace, its a proposal, which I would like to take up and maintain for Distributed Application Runtime. Dapr is an open source and vendor neutral project, its also an event-driven, portable runtime for building microservices on cloud.

I am interested to know the complexity in adding an app and its experience in Civo marketplace.
Also I am new to Dapr, this will give us some experience how to to build resilient, microservice stateless and stateful applications that run on Civo.

**Comment by DoNnMyTh** [comment]
Hello @rajeshradhakrishnanmvk, I Would suggest you give it a look https://github.com/civo/kubernetes-marketplace/blob/master/CONTRIBUTING.md . Apps can be add via Install.sh or via yaml files :), Community Is most welcome to add apps, Before that please make sure you have right Permissions.

**Comment by DoNnMyTh** [comment]
Hello @rajeshradhakrishnanmvk , Thank you for Request. Our marketplace is open to community to make contributions, and as we have updated our market place to support HELM3 and Install.sh files ( example -> https://github.com/civo/kubernetes-marketplace/blob/master/kubevious/install.sh) It is extremely easy. You are most welcome to make a Pull Request.
