### ISSUE TITLE
Additional Catagory: application

### ISSUE THREAD

**Issue by ssmiller25** [civo/kubernetes-marketplace#16]
None of the categories seems to make sense for actual end-user applications, such as Wordpress, Mediawiki, or Nextcloud.  "Application" is pretty board, but trying to make a full taxonomy for all possibilities also seems unnecessary.

**Comment by andyjeffries** [comment]
I agree with this. The plan is always we'd add more categories and rearrange as we add more to the marketplace. When someone submits Wordpress or Mediawiki, I'd say we go for a "CMS" category. Maybe Nextcloud is "File sharing", etc. But it's definitely not the final set-in-stone list of categories as they currently stand.
