### ISSUE TITLE
Simplify Cert-Manager Installation using the official one-line YAML installation method

### ISSUE THREAD

**Issue by sr229** [civo/kubernetes-marketplace#161]
This issue is a:
- [ ] Bug Report
- [x] Enhancement suggestion
- [ ] Feature request

The current cert-manager installation is outdated, and currently doesn't work as intended in the current K3S version. A companion PR,  GH-160  is created to use the official one-line YAML installation instead of the usual Jetstack Helm chart.

**Comment by dscamargo** [comment]
Ref guide https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests

**Comment by sr229** [comment]
Already done via GH-160. Closing.
