### ISSUE TITLE
Add Flux version 2

### ISSUE THREAD

**Issue by ChipWolf** [civo/kubernetes-marketplace#166]
This issue is a:
* [ ] Bug Report
* [ ] Enhancement suggestion
* [x] Feature request

## Enhancement suggestions / feature requests
[Flux2](https://github.com/fluxcd/flux2) is a widely used, extensible open-source continuous delivery solution powered by [GitOps Toolkit](https://toolkit.fluxcd.io/).

**Comment by DoNnMyTh** [comment]
Hello @ChipWolf  , Thank you for Request. Our marketplace is open to community to make contributions, and as we have updated our market place to support HELM3 and Install.sh files ( example -> https://github.com/civo/kubernetes-marketplace/blob/master/kubevious/install.sh) It is extremely easy. You are most welcome to make a Pull Request.

**Comment by saiyam1814** [comment]
Done with #183

**Comment by ChipWolf** [comment]
@saiyam1814 can we re-open this? I don't think Flux is implemented yet in a useful format yet, probably worth making the scope here a little clearer.

**Comment by saiyam1814** [comment]
@ChipWolf can you elaborate here ? we have Flux maintainer @stefanprodan who is working on making the best one-click install experience via the marketplace.

**Comment by ChipWolf** [comment]
Hi @saiyam1814, I elaborate a little further in the [comments](https://github.com/civo/kubernetes-marketplace/pull/183#issuecomment-823664311) on the PR.

> @stefanprodan who is working on making the best one-click install experience via the marketplace.
Is there a different issue for this open or behind the scenes? If so, I apologise.

**Comment by saiyam1814** [comment]
Oops I might have missed the PR comment! 
Have replied there to put it as a suggestion
