### ISSUE TITLE
Configure Pod Security Standard and Validation Failure Action for Kyverno

### ISSUE THREAD

**Issue by fjogeleit** [civo/kubernetes-marketplace#198]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

@realshuting @JimBugwadia

## Enhancement suggestions / feature requests

Kyverno installs the "Default Pod Security Standard" Policies with the validation failure action "audit" as default. I think it's a common use case that users want to install also the "Restricted Pod Security Standard" Policies. It's also common that users want to enforce this policies instead of auditing.

I noticed that it is possible to define parameters in form of selection in the marketplace application. So I would like to create a PR to add a selection for the "Pod Security Standard" and the "Validation Failure Action".

**Comment by JimBugwadia** [comment]
Thanks @fjogeleit! This is a great suggestion!
