### ISSUE TITLE
 Issue and PR templates

### ISSUE THREAD

**Issue by alexellis** [civo/kubernetes-marketplace#20]
It'd be great if there were issue templates to help identify a problem

And PR templates with a check-list that included things like the contributing guide being agreed to:

- [ ] I agree to maintain this submission
- [ ] To the best of my knowledge this is an original work and doesn't contain copyrighted materials
- [ ] I have tested the application (screenshot or text attached below)

Please give the maintainer's GitHub profile below (if not yourself):
- [ ] Username: @alexellis

**Comment by alexellis** [comment]
Examples from inlets (smaller example than OpenFaaS): https://github.com/inlets/inlets/tree/master/.github

**Comment by saiyam1814** [comment]
This is already addressed , once @kaihoffman confirms we can close the issue

**Comment by alexellis** [comment]
This issue is almost a year old 😄 

@kaihoffman I'm sure you know about you can use `Fixes: #20` or `Closes: #20` in your PR or commit next to have issues auto-close.

**Comment by andyjeffries** [comment]
You don't need to be so formulaic about it either for GitHub to recognises it, you can just put "Change X for Z reason to close #20" and it will pick it up. https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by alexellis** [comment]
Good to know. The point was that it wasn't done, and means issues get cleaned up, rather than pinging people one year after the issue was already fixed 🙈

**Comment by saiyam1814** [comment]
Was cleaning up the stale issues and PR's. Don't want it to be a repo with 100's of issues and PR's in open state
