### ISSUE TITLE
Jenkins image on the marketplace uses dated and unofficial Jenkins distribution

### ISSUE THREAD

**Issue by oleg-nenashev** [civo/kubernetes-marketplace#232]
The Jenkins image on the marketplace is dated: https://github.com/civo/kubernetes-marketplace/tree/master/jenkins . I am also not sure why the official Helm chart is not used

This issue is a:
* [x] Bug Report
* [ ] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below: @ 

## Current Behavior

* bitnami/jenkins:2.190.1-debian-9-r14 is used as a base image
* This Jenkins version is 2 years old and contains known security vulnerabilities: https://www.jenkins.io/security/advisories/
* This distribution is not an official one maintained by the Jenkins community: https://www.jenkins.io/download/

## Expected behavior

* An official lated image is used: jenkins/jenkins:lts (there are version tags as well)
* Nice2Have: An official Helm chart is extended: https://github.com/jenkinsci/helm-charts

**Comment by oleg-nenashev** [comment]
CC @ruanbekker @saiyam1814

**Comment by saiyam1814** [comment]
Ruan is the maintainer for the app but I agree to use official image/helm chart for the application install. 
Feel free to raise the PR :)

**Comment by dirien** [comment]
Update the item to the official helm chart of jenkins -> https://github.com/civo/kubernetes-marketplace/pull/243 

https://artifacthub.io/packages/helm/jenkinsci/jenkins
