### ISSUE TITLE
Search option for marketplace

### ISSUE THREAD

**Issue by avinashupadhya99** [civo/kubernetes-marketplace#261]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

## Enhancement suggestions / feature requests

Having a search option for the marketplace makes it easy to search the marketplace instead of switching between tabs and manually searching for the service.

**Comment by avinashupadhya99** [comment]
Just realized, duplicate of https://www.civo.com/account/suggestions/0c1bfe8e

**Comment by dirien** [comment]
I wish the UI would be OSS too, so we could create PRs too

**Comment by NerdyShawn** [comment]
@saiyam1814 I think we can close this stale issue.

I'm not much of a gui user but I do agree that there is value in searching the ever growing list of apps from the marketplace in the dashboard could have some additional value to browse the options to figure out what you can install in a cluster next as a fresh newly welcomed user. Given that the marketplace is available already and [the ui now has a link to this repo ](https://github.com/civo/kubernetes-marketplace)(pictured below)I think we can say we have this condition mostly satisfied but thats me clicking the link and doing a `Ctrl+F` in browser just searching the gitub page unless others had something different in mind for how they were searched and presented in the dashboard.
![image](https://github.com/civo/kubernetes-marketplace/assets/16088118/d09bd6d3-d467-4a54-ab9b-6281172618bc)

Just on the subject the [civo cli](https://github.com/civo/cli) will also give a nice way to list whats installable in a given cluster.
```c
civo k8s apps ls -o custom -f "name category"
acorn management
ambassador-edge-stack architecture
apisix-ingress-controller architecture
argo-rollouts ci_cd
argo-workflows ci_cd
argocd ci_cd
aspnet management
atmo architecture
bitwarden-unified management
blackbox-exporter monitoring
cerbos security
cert-manager architecture
chaos-mesh ci_cd
civo-cluster-autoscaler management
code-server management
dapr architecture
devtron ci_cd
dynamic-pv-scaler storage
edp ci_cd
enroute-onestep architecture
epinio management
falco security
ferretdb database
flux ci_cd
gatekeeper security
ghost management
gimlet management
gitea management
gitlab management
gloo-edge architecture
haproxy architecture
helm management
istio architecture
jenkins ci_cd
joomla management
kafka architecture
keda architecture
keptn ci_cd
ketch management
keycloak security
kong-ingress-controller architecture
kriten architecture
kube-hunter security
kubeclarity security
kubefirst management
kubeflow management
kubenav management
kubernetes-dashboard management
kubernetes-external-secrets security
kubesphere management
kubevela management
kubevious management
kubewarden security
kyverno security
linkerd architecture
litmuschaos ci_cd
loki monitoring
longhorn storage
maesh architecture
mariadb database
metrics-server architecture
minio storage
mongodb database
netdata monitoring
neuvector security
nextcloud management
nexus3 ci_cd
nginx architecture
ngrok-ingress-controller architecture
nodered architecture
openfaas architecture
openobserve monitoring
otomi management
paralus security
parca monitoring
percona-mysql database
permission-manager management
pmm monitoring
polaris security
portainer management
postgresql database
projectsveltos management
prometheus-operator monitoring
pyroscope monitoring
rabbitmq architecture
rancher management
redis database
rekor architecture
reloader architecture
rqlite database
sealed-secrets architecture
selenium ci_cd
shipa management
siglens-oss monitoring
spinkube management
system-upgrade-controller architecture
tekton ci_cd
traefik2-loadbalancer architecture
traefik2-nodeport architecture
unifi-controller management
uptime-kuma monitoring
vault security
volcano management
weavescope monitoring
wordpress management
```

**Comment by NerdyShawn** [comment]
cc: @kunal-kushwaha
