### ISSUE TITLE
Add Factorio

### ISSUE THREAD

**Issue by jdbohrman** [civo/kubernetes-marketplace#29]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[ * ] Feature request

## Enhancement suggestions / feature requests

Can we add Factorio so I can spin up a server for my friend group on Civo and write a blog post about it?

I think it would be a nice community addition. You could even have a community-run Factorio server on Civo infrastructure if you fancy it :)

https://hub.helm.sh/charts/stable/factorio

**Comment by andyjeffries** [comment]
Hey @jdbohrman thanks for taking an interest in submitting an app, but unfortunately at this time we don't really want to host game applications in the marketplace. We don't mind people running them, but it's not an area of hosting that really want to be pushing. Thanks anyway.
