### ISSUE TITLE
Add KubeSphere to the Civo Marketplace

### ISSUE THREAD

**Issue by FeynmanZhou** [civo/kubernetes-marketplace#291]
This issue is a:
* [ ] Bug Report
* [ ] Enhancement suggestion
* [x] Feature request

Hi Civo Team, 

[KubeSphere](http://kubesphere.io/) is an open-source container platform built on Kubernetes, it also supports K3s as the underlying orchestration system. We would like to add KubeSphere to the Civo Marketplace, enabling users to easily manage cloud-native applications and create CI/CD pipelines in multi-cluster and multi-cloud environments.

Thanks.

**Comment by saiyam1814** [comment]
Hey 👋 thats for the PR I will review it over the weekend

**Comment by FeynmanZhou** [comment]
> Hey 👋 thats for the PR I will review it over the weekend

Okay, we will raise a PR soon after testing it from our side.

**Comment by saiyam1814** [comment]
Let me know if you need any help @FeynmanZhou
