### ISSUE TITLE
Add Spinnaker

### ISSUE THREAD

**Issue by jdbohrman** [civo/kubernetes-marketplace#30]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[ * ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests

Adding Spinnaker to the marketplace might be a nice touch

**Comment by andyjeffries** [comment]
One of our users on the Kube100 slack channel feels that Spinnaker is a huge piece of software so may not be appropriate for the k3s service (given we don't currently have a system where marketplace apps can say "I need a minimum of X resources"). Your thoughts @jdbohrman ?

**Comment by srinivasraja54** [comment]
Let me know if spinnaker needs to be added. I'll give a shot. It would take 2-3 large nodes to run

**Comment by saiyam1814** [comment]
Spinnaker is too big IMO for K3s, once we have the mechanism of highlighting minimum memory/CPU for an app we can revisit this, till then I would close this issue.
