### ISSUE TITLE
Add NGINX Ingress Controller 

### ISSUE THREAD

**Issue by armujahid** [civo/kubernetes-marketplace#33]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[x] Feature request

## Enhancement suggestions / feature requests
In architecture section I think we should add [nginx ingress controller](https://kubernetes.github.io/ingress-nginx/). Currently it can be installed using `helm install my-nginx stable/nginx-ingress`. We just need to ensure that Traefik Ingress controller isn't selected during cluster creation. Otherwise we will get `FailedScheduling` issue for ingress controller pods because of ingress port unavailability.

**Comment by sr229** [comment]
I don't think we're quite ready for NGINX ingresses yet, Rancher seems to fail to route properly. See #50

**Comment by AugustasV** [comment]
I checked the link @sr229 provided, so I could see there is no issues with that. Also it's possible to spin up a cluster via cli without Traefik. See [https://github.com/civo/cli#starting-a-cluster-without-default-applications](url)

**Comment by saiyam1814** [comment]
https://github.com/civo/kubernetes-marketplace/tree/master/nginx
Already exists now!
