### ISSUE TITLE
A Kubeflow application

### ISSUE THREAD

**Issue by Rishit-dagli** [civo/kubernetes-marketplace#341]
This issue is a:
* [ ] Bug Report
* [ ] Enhancement suggestion
* [x] Feature request

## Enhancement suggestions / feature requests

It would be pretty helpful to have a Kubeflow application on the Civo marketplace. Kubeflow is quite popular in the Machine Learning community as can be seen in [kubeflow/kubeflow](https://github.com/kubeflow/kubeflow) and would help the overall Civo community.

> The Kubeflow project is dedicated to making deployments of machine learning (ML) workflows on Kubernetes simple, portable and scalable. Our goal is not to recreate other services, but to provide a straightforward way to deploy best-of-breed open-source systems for ML to diverse infrastructures. Anywhere you are running Kubernetes, you should be able to run Kubeflow.  —[kubeflow.org](https://www.kubeflow.org/)

I would love to contribute this if it sounds like a right fit for the Civo marketplace.

I propose using [Kubeflow Manifests](https://github.com/kubeflow/manifests) to create this application. I tried deploying Kubeflow on a Civo cluster and running some preliminary tests on installing using the Manifests and would propose going forward this way if we go ahead with this issue.

**Comment by saiyam1814** [comment]
@Rishit-dagli I am onboard with adding kubeflow

**Comment by Rishit-dagli** [comment]
Before I start working on this, I had a question though: as far as I have observed you often need to apply the generated Kubernetes resource configurations at least twice since some resources can only be created afterr other ones are ready. Is the resource configuration applied to the Civo cluster from `app.yaml` in a loop until all the resources are ready?

**Comment by saiyam1814** [comment]
kubectl gives us a command to check on this 
eg `kubectl wait --for=condition=available --timeout=300s deployment/nginx
`

**Comment by Rishit-dagli** [comment]
Yes, but using an `app.yaml` does not support this, right? Or did I miss something

**Comment by saiyam1814** [comment]
you can use install.sh and app.yaml both in a single marketplace application
