### ISSUE TITLE
A Volcano app

### ISSUE THREAD

**Issue by Rishit-dagli** [civo/kubernetes-marketplace#343]
This issue is a:

* [x] Feature request

## Enhancement suggestions / feature requests

Adding an application for [Volcano](https://volcano.sh/) would be pretty useful for a lot of folks. Volcano is a very popular batch scheduling system and is also an incubating CNCF project. Volcano supports quite a few machine learning frameworks and is quite popular in the community as well.

> Volcano is system for running high-performance workloads on Kubernetes. It features powerful batch scheduling capability that Kubernetes cannot provide but is commonly required by many classes of high-performance workloads, including: Machine learning/Deep learning, Bioinformatics/Genomics, Other big data applications

—https://volcano.sh/en/

I would love to contribute this if it sounds like a right fit for the Civo marketplace.

**Comment by saiyam1814** [comment]
I know it is a CNCF project, what are some of the use-cases for this ?

**Comment by Rishit-dagli** [comment]
Sure, so Volcano is used quite a lot for high-performance computing workloads on Kubernetes. It is used especially for machine learning and HPC tasks and introduces support for gang scheduling, GPU affinity scheduling, distributed training, and related aspects (batch creation, queue management, and more).

**Comment by saiyam1814** [comment]
So Civo does not have a GPU offering Yet, will this be useful for CPU only nodes?

**Comment by Rishit-dagli** [comment]
Yes, most of the capabilities of Volcano will still be useful for CPU nodes.

**Comment by saiyam1814** [comment]
Ok cool lets get that added then
