### ISSUE TITLE
Helm Version Upgrade

### ISSUE THREAD

**Issue by cablespaghetti** [civo/kubernetes-marketplace#39]
This issue is a:
[ ] Bug Report
[x] Enhancement suggestion
[ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below: N/A

## Enhancement suggestions / feature requests
Please supply a newer Helm version. If not 3.1 at least 2.16 which is more commonly installed than 2.14 at this point in time.

**Comment by Ludea** [comment]
no ETA on this ?

**Comment by AugustasV** [comment]
I would like to help with this task.

**Comment by AugustasV** [comment]
> no ETA on this ?

Helm 3 works differently then Helm 2, so it's not needed anymore.

**Comment by saiyam1814** [comment]
It's done, we only support helm3 now!
