### ISSUE TITLE
Cert Manager Upgrade

### ISSUE THREAD

**Issue by cablespaghetti** [civo/kubernetes-marketplace#40]
This issue is a:
[ ] Bug Report
[x] Enhancement suggestion
[ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below: @alexellis 

## Enhancement suggestions / feature requests
Newer cert-manager version e.g. 0.14. 0.11 is getting quite old now.

**Comment by alexellis** [comment]
Hi @cablespaghetti, can you list out any breaking changes from the docs? There are Civo learn guides that @kaihoffman may need to update in accordance with this change.

Alex

**Comment by cablespaghetti** [comment]
Sure. Included things the Helm chart won't automatically solve for you.

*0.12* - https://cert-manager.io/docs/installation/upgrading/upgrading-0.11-0.12/
_Changes to the Vault Kubernetes Auth Mount Path_

> If you are using Kubernetes authentication for Vault Issuers then there has been a change to the required mount path. This value now requires the entire mount path. For example, if the previous path had been set to kubernetes, the new path will now require /v1/auth/kubernetes. 

*0.13* - https://cert-manager.io/docs/installation/upgrading/upgrading-0.12-0.13/
None

*0.14* - https://cert-manager.io/docs/installation/upgrading/upgrading-0.13-0.14/
This will be the interesting one. I'm not sure how you would handle this for users:

> Due to changes in the Deployment selector you will need to remove the deployments first before being able to upgrade.

> You should run the following before upgrading:

> $ kubectl delete -n cert-manager deployment cert-manager cert-manager-cainjector cert-manager-webhook

> If you’re using Helm to install cert-manager with a deployment name different than cert-manager you might need to change the deployment names in the command above.

> This will delete the deployment so they can be replaced when you apply the upgrade. This step will not affect any existing certificates but will stop renewal or new issuance while upgrading.

**Comment by andyjeffries** [comment]
We don't (currently) provide marketplace app upgrades, so the breaking upgrade changes won't matter as much. This is more about changes required to the documentation (for @kaihoffman) which I didn't see any of above?

**Comment by alexellis** [comment]
This may impact upon learn guides.

**Comment by sr229** [comment]
Already done via #160 and preceeding cert-manager PRs so this may be closed now, @saiyam1814.

**Comment by DoNnMyTh** [comment]
Cert manager Updated, Can be closed.
