### ISSUE TITLE
wrong dependency on helm in prometheus operator app

### ISSUE THREAD

**Issue by jeka** [civo/kubernetes-marketplace#42]
This issue is a:
[X ] Bug Report
[ ] Enhancement suggestion
[ ] Feature request

@akosveres 

The manifest of prometheus operator app specifies helm as a dependency that is not needed.

**Comment by jeka** [comment]
@akosveres, I created a #44 solving this.

**Comment by Waterdrips** [comment]
This is fixed, @andyjeffries or @jeka can you close this issue?

**Comment by jeka** [comment]
I can I guess.
