### ISSUE TITLE
Add Uptime-Kuma as new application for Civo marketplace

### ISSUE THREAD

**Issue by dirsigler** [civo/kubernetes-marketplace#421]
This issue is a:
* [ ] Bug Report
* [ ] Enhancement suggestion
* [X] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
If you are requesting an enhancement to a feature already present, or a new feature, please outline below the feature you would like to see, and how it would benefit you and the wider Civo Kubernetes userbase:

I would like to add the popular [Uptime-Kuma](https://github.com/louislam/uptime-kuma) as an additional application for the Civo Marketplace.

**Comment by NerdyShawn** [comment]
@saiyam1814 I think this one can be closed, it looks like it was satisfied via 
- #603
