### ISSUE TITLE
Update kubernetes-external-secrets marketplace app

### ISSUE THREAD

**Issue by narenarjun** [civo/kubernetes-marketplace#443]
This issue is a:
* [ x ] Bug Report
* [ ] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Bug Reports

The application  "kubernetes-external-secrets" install for kubernetes points to the old Github page. This should be updated and should point to the current releases found in the new github page:  https://github.com/external-secrets/external-secrets. This will improve and provide the new features available via civo marketplace install.  

The updates should be done in `install.sh`, `manifest.yaml`,`post_install.md` files for the "kubernetes-external-secrets" app.

@dirien is the maintainer for this app.

**Comment by dirien** [comment]
Done, PR is created!

**Comment by narenarjun** [comment]
Thanks a lot @dirien , I will get this reviewed.
