### ISSUE TITLE
Add security category in civo marketplace (with tools like kube-scan, polaris)

### ISSUE THREAD

**Issue by milindchawre** [civo/kubernetes-marketplace#46]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[ * ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
While exploring civo kubernetes service. What I really missed is deploying any security related tools on k8s through marketplace.
As a start, I would like to add tools like [kube-scan](https://github.com/octarinesec/kube-scan) and [polaris](https://github.com/FairwindsOps/polaris) to the marketplace.

**Comment by curx** [comment]
maybe you can give [starboard](https://github.com/aquasecurity/starboard) a try

**Comment by andyjeffries** [comment]
Feel free to add PRs for any security tools you'd recommend. We're happy to make a new category for them.

**Comment by andyjeffries** [comment]
I've added the category to the official supported list.
