### ISSUE TITLE
Add Paralus as an application to CIVO Marketplace

### ISSUE THREAD

**Issue by niravparikh05** [civo/kubernetes-marketplace#464]
This issue is a:
* [ ] Bug Report
* [ ] Enhancement suggestion
* [x] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
If you are requesting an enhancement to a feature already present, or a new feature, please outline below the feature you would like to see, and how it would benefit you and the wider Civo Kubernetes userbase:

I would like to add the popular [Paralus](https://www.paralus.io/) as an additional application for the Civo Marketplace.

**Comment by NerdyShawn** [comment]
@saiyam1814 
I think this issue should be closed, the paralus app was added via 
- https://github.com/civo/kubernetes-marketplace/pull/469

**Comment by NerdyShawn** [comment]
cc: @kunal-kushwaha
