### ISSUE TITLE
Update Joomla app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#479]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests

Currently, we have Joomla version 3.9.24 installed by Civo marketplace as a newer version 4.3.3 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Joomla on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@keithhubner and @DoNnMyTh are the maintainers for this app, so I request you to please take a look into this.

**Comment by DoNnMyTh** [comment]
Sure @aakashnagpal4567 I'll update it.

**Comment by NerdyShawn** [comment]
Hello! 👋🏼 The available version is now newer than the requested version in the issue, we should be good to close this. cc: @kunal-kushwaha 
https://github.com/civo/kubernetes-marketplace/blob/42eb55a95ab8c7283451b0ddc07fa16666a0f8ab/joomla/manifest.yaml#L4
