### ISSUE TITLE
Update Kubefirst app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#480]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests

Currently, we have Kubefirst version 2.1.19 installed by Civo marketplace as a newer version 2.2.2 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Kubefirst on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@jarededwards I request you to please take a look into this.

**Comment by jarededwards** [comment]
hi @aakashnagpal4567 , thanks for the report. we had a pull request merged a couple days ago which bumps to our latest version (2.2.5) and im not sure what needs to take place on the civo side to get this into production. @saiyam1814 can you help us understand how to get updates into marketplace? I don't know if we just need to catch a release internally at Civo that has not happened yet. I'll keep an eye on changes that go in here

**Comment by NerdyShawn** [comment]
Verified that kubefirst version available is greater than the requested version in the issue.
https://github.com/civo/kubernetes-marketplace/blob/42eb55a95ab8c7283451b0ddc07fa16666a0f8ab/kubefirst/manifest.yaml#L3

cc: @kunal-kushwaha  this issue should be good to close as we have an even newer version than requested version on this issue from last year at this point.
