### ISSUE TITLE
Update Cert Manager app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#490]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions/feature requests

Currently, we have Cert Manager version v1.11.4 installed by Civo marketplace as a newer version v1.12.0 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Cert Manager on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@alexellis I request you to please take a look into this

**Comment by alexellis** [comment]
Hi @aakashnagpal4567 I'm not involved with Civo or the marketplace, please don't tag me as I get a lot of notifications as it is and find it hard to filter them all.

@kaihoffman will know who to call for this.

**Comment by alexellis** [comment]
@kaihoffman I'm not a Civo maintainer, please could you remove my name and replace it with one of your team? https://github.com/civo/kubernetes-marketplace/blob/master/cert-manager/manifest.yaml#L4

**Comment by NerdyShawn** [comment]
@saiyam1814 I think this is now solved now, updatecli is successfully running against the repo.
- https://github.com/civo/kubernetes-marketplace/pull/755

I also drafted up a PR here to update the maintainer for cert-manager for Alex. I just wanted to make sure that I got your tag right and or if there were any other maintainer tags/emails your on you want me to update as well for consistency's sake.
- https://github.com/civo/kubernetes-marketplace/pull/773

**Comment by alexellis** [comment]
@NerdyShawn I am not the maintainer of the cert-manager app for Civo, please feel free to tag a staff member of the Civo team for review.

**Comment by NerdyShawn** [comment]
cc: @kunal-kushwaha this one should be solved and I have attached a draft pr to update the maintainer if you get a moment for review. I had some questions one which was the most appropriate tag to use for the maintainer that we had talked about earlier.
