### ISSUE TITLE
Add more storage options

### ISSUE THREAD

**Issue by sr229** [civo/kubernetes-marketplace#51]
This issue is a:
- [ ] Bug Report
- [ ] Enhancement suggestion
- [x] Feature request

Currently we only have Longhorn, however, if you're using Rancher, you'll be able to deploy anything other than Longhorn (such as OpenEBS, which is a much more better solution since it supports RWX (Read-Write-Many) vs Longhorn).

**Comment by andyjeffries** [comment]
We're happy to accept PRs for any marketplace apps that can be installed to the cluster. StorageOS, OpenEBS, etc.
