### ISSUE TITLE
Update Selenium app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#510]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions/feature requests
Currently, we have Selenium version 3.141.59-r1 installed by Civo marketplace as a newer version 4.10.0 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Selenium on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@scndel is the maintainer for this app, so I request you to please take a look into this.

**Comment by scndel** [comment]
Indeed it should be updated for a long time, happy that this app is useful. 
Done on my side ! #528

**Comment by NerdyShawn** [comment]
cc: @kunal-kushwaha it looks like this one might be close-able as well.
