### ISSUE TITLE
Update Okteto app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#512]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions/feature requests
Currently, we have Okteto version 0.9.6 installed by Civo marketplace as a newer version 1.10 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Okteto on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@rberrelleza is the maintainer for this app, so I request you to please take a look into this.

**Comment by NerdyShawn** [comment]
Hello! 👋🏼  We should be able to close this one as okteto is currently not featured on the marketplace.
**Reference:**
- https://github.com/civo/kubernetes-marketplace/pull/557

cc: @kunal-kushwaha
