### ISSUE TITLE
Update Sealed Secrets app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#513]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
Currently, we have Sealed Secrets version v0.12.4 installed by Civo marketplace as a newer version v0.23.0 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Sealed Secrets on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@soukron is the maintainer for this app, so I request you to please take a look into this.

**Comment by NerdyShawn** [comment]
Hello! 👋🏼  Looking at this moment in time we have surpassed the requested version. cc: @kunal-kushwaha this one should be ready for closing.
https://github.com/civo/kubernetes-marketplace/blob/42eb55a95ab8c7283451b0ddc07fa16666a0f8ab/sealed-secrets/manifest.yaml#L4
