### ISSUE TITLE
Update Kubernetes External Secrets app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#515]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
Currently, we have Kubernetes External Secrets version 0.8.3 installed by Civo marketplace as a newer version 0.8.5 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Kubernetes External Secrets on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@dirien is the maintainer for this app, so I request you to please take a look into this.

**Comment by dirien** [comment]
go for it!🎉

**Comment by NerdyShawn** [comment]
Hello! 👋🏼 This requested version has been satisfied via https://github.com/civo/kubernetes-marketplace/pull/715
- https://github.com/civo/kubernetes-marketplace/blob/42eb55a95ab8c7283451b0ddc07fa16666a0f8ab/kubernetes-external-secrets/manifest.yaml#L4
cc: @kunal-kushwaha
