### ISSUE TITLE
Update Tekton app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#520]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
Currently, we have Tekton version v0.44.0 installed by Civo marketplace as a newer version v0.50.0 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Tekton on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@ssmiller25 is the maintainer for this app, so I request you to please take a look into this.

**Comment by NerdyShawn** [comment]
cc: @kunal-kushwaha This one can be closed `v0.50.5` is[ available in marketplace](https://github.com/civo/kubernetes-marketplace/blob/42eb55a95ab8c7283451b0ddc07fa16666a0f8ab/tekton/manifest.yaml#L4)
