### ISSUE TITLE
Update Loki Stack app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#524]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions/feature requests
Currently, we have Loki Stack version v2.1.2 installed by Civo marketplace as a newer version v2.8.3 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Loki Stack on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@ssmiller25 is the maintainer for this app, so I request you to please take a look into this.

**Comment by ssmiller25** [comment]
Latest version of loki-stack is 2.9.11, so updating to that version

**Comment by NerdyShawn** [comment]
Hello! 👋🏼 The requested version has been satisfied with an even newer version. cc: @kunal-kushwaha should be ready to close this isue.
https://github.com/civo/kubernetes-marketplace/blob/42eb55a95ab8c7283451b0ddc07fa16666a0f8ab/loki/manifest.yaml#L4
