### ISSUE TITLE
Palarus logo fix

### ISSUE THREAD

**Issue by saiyam1814** [civo/kubernetes-marketplace#538]
@aakashnagpal4567 can you fix Palarus logo please ? its greater than 20kb so erroring out on CI builds

**Comment by NerdyShawn** [comment]
@saiyam1814 I believe this is ready to be closed.

I just validated that the current logo.png is under 20kb
```c
date && du -sh logo.png 
Tue May 14 07:39:06 PM EDT 2024
16K	logo.png
```
Found a [commit where it was resized.](https://github.com/civo/kubernetes-marketplace/commit/b567bc9222f5a983b4e0a9e87e6e803423f8d675)

**Comment by NerdyShawn** [comment]
cc: @kunal-kushwaha
