### ISSUE TITLE
Support NFS provisioner

### ISSUE THREAD

**Issue by ulm0** [civo/kubernetes-marketplace#55]
This issue is a:
[x] Feature request

## Enhancement suggestions / feature requests

It would be good to have the official nfs-provisioner (https://github.com/kubernetes-incubator/external-storage/tree/master/nfs)

**Comment by sr229** [comment]
Based on my testing NFS provisioner barely worked in K3s, especially when pared with Rancher's block storage.

**Comment by ulm0** [comment]
I've got nfs-provisioner deployed on civo k3s @sr229 and it's working, though civo still need to improve the masters performance 'cause it shows some connectivity issues from time to time causing the nfs-provisioner to fail since it needs to be able to talk to the api-server

**Comment by saiyam1814** [comment]
@ulm0 can you check with the new hardware that we have now in place? 
If this works fine we can close the issue!

**Comment by simaiden** [comment]
> I've got nfs-provisioner deployed on civo k3s @sr229 and it's working, though civo still need to improve the masters performance 'cause it shows some connectivity issues from time to time causing the nfs-provisioner to fail since it needs to be able to talk to the api-server

How you managed to deploy the nfs - provisioner? I even can't mount a pv-pvc in a pod running in the kubernet cluster using nfs-server deployed in a compute instance.

Thanks for your help!

**Comment by sr229** [comment]
Just a update, Rancher's longhorn has a NFS Provisioner class, so I think we can safely close this since Longhorn can provide this already.

**Comment by NerdyShawn** [comment]
Oh, also the original mentioned repo was archived 2020, and the actively maintained one is over here now.
- https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner

**Comment by NerdyShawn** [comment]
cc: @kunal-kushwaha
