### ISSUE TITLE
Argo CD installation failure

### ISSUE THREAD

**Issue by narenarjun** [civo/kubernetes-marketplace#606]
This issue is a:
* Bug Report

## Bug Reports

- Expected behavior: 
   Argo CD installed from the marketplace should create the necessary k8s resources for the Argo CD to be accessible. 

- Encountered behavior:
    Argo CD was not installed in the expected namespace. While inspecting the cluster, I got the following logs: 

```shell
 naren@promac  ~/Downloads  kubectl get pods
NAME                                 READY   STATUS      RESTARTS   AGE
install-traefik2-nodeport-ar-472d5   0/1     Completed   0          11m
install-argo-cd-argo-1-3e7e-v9bzl    0/1     Error       0          11m
 naren@promac  ~/Downloads  kubectl logs install-argo-cd-argo-1-3e7e-v9bzl
{"time":"2023-11-02T08:08:54.570112658Z","level":"INFO","msg":"Cloneing git repo https://github.com/civo/kubernetes-marketplace\n"}
{"time":"2023-11-02T08:08:54.570604197Z","level":"INFO","msg":"Creating temp dir to clone git repo"}
{"time":"2023-11-02T08:08:54.574601022Z","level":"INFO","msg":"Created temp dir: /tmp/prefix948679108"}
{"time":"2023-11-02T08:08:57.935896603Z","level":"INFO","msg":"Validating that app exists: argo-cd\n"}
Error: stat /tmp/prefix948679108/argo-cd: no such file or directory
Usage:
  marketplace-installer install [flags]

Examples:
install <app name>

Flags:
  -h, --help   help for install

Global Flags:
  -d, --git-url string   The git repo to clone from (default "https://git.civo.com/civo/marketplace.git")


```

- The steps to recreate the behaviour that you are reporting:
  1. create a new cluster by selecting argo cd under CI/CD in the step 7 marketplace. 
  2. then access the cluster by using kubectl with the clusters kubeconfig file
  3. then list all pods in the default namespace and log the pod which shows error with kubectl cli 

This seems to be a path-missing issue encountered during the installation by the installer.

**Comment by narenarjun** [comment]
@aakashnagpal4567 please take a look into this issue. thank you

**Comment by aakashnagpal4567** [comment]
I found that install.sh, the script is failing, what I have done, is I have created a Kubernetes cluster and installed the argocd manually, as step by step given in instal.sh file. I have successfully installed the argocd, but when I installed the argocd using civo marketplace in another new cluster, it failed.
Tagging @davenull as he is working on an issue related to this.
