### ISSUE TITLE
New Category Request

### ISSUE THREAD

**Issue by habil** [civo/kubernetes-marketplace#61]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[X] Feature request

## Enhancement suggestions / feature requests

Would you consider adding a new category under Tools & Frameworks? I want to add RabbitMQ product but I couldn't choose a suitable category.

**Comment by andyjeffries** [comment]
To be honest, we'd be happy with it under Databases or Architecture. At the moment we want to tightly control categories only splitting them out when we have sufficient apps in there to need them. if we get a few more similar things, then we would likely split it out.

**Comment by habil** [comment]
Okay. I continue with the Architecture category. Thank you.
