### ISSUE TITLE
Add support for deploying projectsveltos

### ISSUE THREAD

**Issue by gianlucam76** [civo/kubernetes-marketplace#690]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If it is OK to add [projectsveltos](https://github.com/projectsveltos) I am happy to take care of that.

Thank you

**Comment by saiyam1814** [comment]
YEs feel free to raise the PR

**Comment by gianlucam76** [comment]
Pushed [here](https://github.com/civo/kubernetes-marketplace/pull/696)
