### ISSUE TITLE
Open source logging solution 

### ISSUE THREAD

**Issue by Cybervu** [civo/kubernetes-marketplace#74]
This issue is a: Feature request

A logging solution like EFK or Graylog will be very help full.

**Comment by fgrehm** [comment]
Another option could be https://grafana.com/docs/loki/latest/ :)

**Comment by saiyam1814** [comment]
the civo marketplace is heavily driven by the community so feel free to contribute the apps to the marketplace

**Comment by saiyam1814** [comment]
@Cybervu and @fgrehm Loki has been added to the marketplace, feel free to give it a spin :)
