### ISSUE TITLE
Add netdata monitoring tool

### ISSUE THREAD

**Issue by milindchawre** [civo/kubernetes-marketplace#89]
This issue is a:
[ ] Bug Report
[ ] Enhancement suggestion
[*] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
If you are requesting an enhancement to a feature already present, or a new feature, please outline below the feature you would like to see, and how it would benefit you and the wider Civo Kubernetes userbase:

**Comment by milindchawre** [comment]
The netdata helm chart is [not yet official available](https://github.com/netdata/helmchart/issues/74). FOr now I tried the manual way of configuring netdata and it seems to be working fine. I will wait until their official helm chart is ready.

**Comment by OdysLam** [comment]
That's awesome @milindchawre. Thanks for the love!

**Comment by saiyam1814** [comment]
Would be awesome to see netdata in civo marketplace
