### ISSUE TITLE
Wordpress installation is not triggered correctly

### ISSUE THREAD

**Issue by javicv** [civo/kubernetes-marketplace#96]
This issue is a:
[x] Bug Report
[ ] Enhancement suggestion
[ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:
@javicv 

## Bug Reports
Wordpress installation is not triggered correctly. When you select "Wordpress" from marketplace applications, it's shown as installed with its dependencies but if check the cluster neither of them are installed (longhorn, mariadb, wordpress)
![image](https://user-images.githubusercontent.com/18577298/94672866-26cc0200-0316-11eb-9ad1-4355296042fa.png)

In a new cluster I tried to install MariaDB and it triggers Longhorn's installation and MariaDB is installed afterwards, then I select Wordpress from the marketplace and the application isn't installed, I can't see the pvc, deployment, service or ingress in my cluster with kubectl.

Is there something wrong with the application template or is it caused by the marketplace installer?

**Comment by saiyam1814** [comment]
let me try

**Comment by saiyam1814** [comment]
I installed on a fresh  cluster, it worked:
![image](https://user-images.githubusercontent.com/8190114/94706577-fd37c880-035f-11eb-87f0-e58306b3f70a.png)
please verify

**Comment by javicv** [comment]
Thanks @saiyam1814 It's working now.
I tihink this issue can be closed.
